### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by 0pcom** [redcurse/SynthCat-Brick-Breaker#2]
cx version 0.6.2
os:archlinux

```
$ cx loop_tracker.cx loop_limiter.cx main.cx
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.ShorthandExpression(0xc00009e5c8, 0x1, 0x1, 0xc00008f460, 0x2, 0x2, 0x9, 0xc00008f460, 0x2, 0x2)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/actions/expressions.go:288 +0x4f6
main.yyParse(0x9b0e20, 0xc0005002d0, 0xc0005002d0)
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/cxgo.go:2136 +0x6eaf
main.main()
	/home/amherag/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8758 +0x622
```

**Comment by corpusc** [comment]
indeed, this is a problem.  i'm using CX 0.7beta.  the full public release of 0.7 is supposed to happen Saturday.

hi RedCurse, i'm interested in fixing this for you, if you'd rather not spend the time to do it yourself.
there are more people asking about working CX game source codes lately, so it would be nice to have more.

would you be interested in me doing this and making a Pull Request?

**Comment by redcurse** [comment]
Go for it. Sorry I haven't been able to spend the time to look at it.
Thanks!
